### ISSUE TITLE
Call to `rm` fails on Windows

### ISSUE THREAD

**Issue by stevelove** [anoskov/rsa-ex#1]
I work on a team that develops on different operating systems. When RsaEx generates key files, it then tries to remove them using `rm`, i.e. `System.cmd "rm", ["-f", private_key]`.

Could this be replaced with Elixir's [File.rm/1](http://elixir-lang.org/docs/stable/elixir/File.html#rm/1) to support multiple platforms?

I'm happy to submit a pull request if that seems like the right solution.

**Comment by anoskov** [comment]
Thanks for your issue, @stevelove! I don't know why I used System rm instead File.rm/1, my bad. But now I have fixed this issue. It's look good now?

**Comment by stevelove** [comment]
Thanks for the fast fix. It's working perfectly now!

**Comment by anoskov** [comment]
Nice! Good luck!
